package com.saleh.tamimaccounts

import android.app.Activity
import android.app.AlertDialog
import android.os.Bundle
import android.content.*
import android.graphics.Color
import android.net.Uri
import android.provider.Settings
import android.view.*
import android.view.inputmethod.InputMethodManager
import android.widget.*
import java.text.DecimalFormat
import java.text.SimpleDateFormat
import java.util.*

class ModernActivity : Activity() {
    private lateinit var db: DatabaseHelper
    private lateinit var body: LinearLayout
    private val money = DecimalFormat("#,##0.##")
    private val green = Color.rgb(25, 130, 85)
    private val red = Color.rgb(190, 55, 55)
    private val muted = Color.rgb(105, 105, 105)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.decorView.layoutDirection = View.LAYOUT_DIRECTION_RTL
        db = DatabaseHelper(this)
        buildShell()
        dashboard()
    }
    private fun dp(v:Int)= (v*resources.displayMetrics.density).toInt()
    private fun tv(s:String,size:Float=15f,bold:Boolean=false,color:Int=Color.DKGRAY):TextView=TextView(this).apply{ text=s;textSize=size;setTextColor(color);if(bold)setTypeface(typeface,1);setPadding(dp(8),dp(6),dp(8),dp(6)) }
    private fun btn(s:String, action:()->Unit)=Button(this).apply{ text=s;setOnClickListener{action()};minHeight=dp(48);isAllCaps=false }
    private fun card()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(8),dp(12),dp(8));setBackgroundColor(Color.WHITE)}
    private fun buildShell(){
        val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(247,248,250));layoutDirection=View.LAYOUT_DIRECTION_RTL}
        val top=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(6),dp(10),dp(6))}
        top.addView(tv("بقالة العزي",20f,true,green),LinearLayout.LayoutParams(0,dp(56),1f));top.addView(btn("↻"){dashboard()},LinearLayout.LayoutParams(dp(58),dp(52)))
        root.addView(top)
        val scroll=ScrollView(this);body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),dp(4),dp(10),dp(85))};scroll.addView(body);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f))
        val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(4,2,4,4)}
        listOf("الرئيسية" to {dashboard()},"الحسابات" to {accounts()},"الفواتير" to {invoices()},"المخزون" to {inventory()},"المزيد" to {more()}).forEach{(s,f)->nav.addView(btn(s){f()},LinearLayout.LayoutParams(0,dp(58),1f))}
        root.addView(nav)
        setContentView(root)
    }
    private fun setPage(title:String){body.removeAllViews();body.addView(tv(title,24f,true,green));body.addView(View(this).apply{setBackgroundColor(Color.LTGRAY)},LinearLayout.LayoutParams(-1,1).apply{setMargins(0,0,0,dp(8))})}
    private fun section(title:String){body.addView(tv(title,17f,true,Color.DKGRAY))}
    private fun dashboard(){setPage("الرئيسية");val cs=db.customers();val tx=cs.sumOf{db.transactions(it.id).size};val products=db.products().size;val box=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};listOf("الحسابات\n${cs.size}" to green,"العمليات\n$tx" to Color.rgb(70,100,180),"الأصناف\n$products" to Color.rgb(145,95,40)).forEach{(s,c)->box.addView(card().apply{addView(tv(s,18f,true,c))},LinearLayout.LayoutParams(0,dp(90),1f).apply{setMargins(3,3,3,3)})};body.addView(box);section("اختصارات");body.addView(btn("＋ إضافة حساب"){customerDialog()});body.addView(btn("＋ إضافة عملية"){chooseCustomerForTx()});body.addView(btn("＋ فاتورة بيع"){invoiceDialog("SALE")});body.addView(btn("＋ فاتورة شراء"){invoiceDialog("PURCHASE")});body.addView(btn("＋ إضافة صنف"){productDialog()})}
    private fun accounts(){setPage("الحسابات");val search=EditText(this).apply{hint="بحث باسم العميل أو الهاتف";textSize=15f};body.addView(search,LinearLayout.LayoutParams(-1,dp(52)).apply{setMargins(0,0,0,dp(8))});body.addView(btn("＋ إضافة حساب جديد"){customerDialog()});db.customers().forEach{c->val v=card();v.addView(tv(c.name,17f,true));v.addView(tv(if(c.phone.isBlank())"بدون هاتف" else c.phone,13f,false,muted));v.addView(tv("الرصيد: ${money.format(c.balance)}",16f,true,if(c.balance>0)red else green));val actions=LinearLayout(this);actions.addView(btn("فتح الحساب"){ledger(c.id)},LinearLayout.LayoutParams(0,dp(46),1f));actions.addView(btn("حذف"){confirm("حذف الحساب وجميع عملياته؟"){db.deleteCustomer(c.id);accounts()}},LinearLayout.LayoutParams(0,dp(46),1f));v.addView(actions);body.addView(v,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(5),0,dp(5))})}}
    private fun ledger(id:Long){val c=db.customer(id)?:return;setPage(c.name);val head=card();head.addView(tv("حساب العميل",13f,false,muted));head.addView(tv(c.name,23f,true,green));head.addView(tv("الهاتف: ${c.phone.ifBlank{"—"}}",14f));head.addView(tv("الرصيد: ${money.format(c.balance)}",19f,true,if(c.balance>0)red else green));body.addView(head);val ar=LinearLayout(this);ar.addView(btn("＋ إضافة عملية"){transactionDialog(c)},LinearLayout.LayoutParams(0,dp(50),1f));ar.addView(btn("تعديل"){customerDialog(c)},LinearLayout.LayoutParams(0,dp(50),1f));ar.addView(btn("مشاركة"){share(c)},LinearLayout.LayoutParams(0,dp(50),1f));body.addView(ar);section("كشف الحساب");val txs=db.transactions(id);var run=0.0;txs.forEach{t->run+=if(t.type=="DEBIT")t.amount else -t.amount;val v=card();v.addView(tv("${if(t.type=="DEBIT")"عليه" else "له"}   ${money.format(t.amount)} ${t.currency}",17f,true,if(t.type=="DEBIT")red else green));v.addView(tv(t.note.ifBlank{"بدون بيان"},14f));v.addView(tv("${t.date}   •   الرصيد بعد العملية: ${money.format(run)}",12f,false,muted));v.setOnLongClickListener{confirm("حذف العملية؟"){db.deleteTransaction(t.id);ledger(id)};true};body.addView(v,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(4),0,dp(4))})};body.addView(btn("حذف الحساب بالكامل"){confirm("سيتم حذف الحساب وكل عملياته نهائياً"){db.deleteCustomer(id);accounts()}})}
    private fun invoices(){setPage("الفواتير");val add=LinearLayout(this);add.addView(btn("＋ فاتورة بيع"){invoiceDialog("SALE")},LinearLayout.LayoutParams(0,dp(54),1f));add.addView(btn("＋ فاتورة شراء"){invoiceDialog("PURCHASE")},LinearLayout.LayoutParams(0,dp(54),1f));body.addView(add);section("الفواتير المحفوظة");query("SELECT i.id,i.type,i.date,i.total,i.paid,COALESCE(c.name,COALESCE(s.name,'')) FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id LEFT JOIN suppliers s ON s.id=i.supplier_id ORDER BY i.id DESC",null){cur->val v=card();val type=cur.getString(1);v.addView(tv("${if(type=="SALE")"فاتورة بيع" else "فاتورة شراء"} #${cur.getLong(0)}",17f,true,green));v.addView(tv("${cur.getString(5)}   •   ${cur.getString(2)}",13f,false,muted));v.addView(tv("الإجمالي: ${money.format(cur.getDouble(3))}   |   المدفوع: ${money.format(cur.getDouble(4))}",15f,true));body.addView(v,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(4),0,dp(4))})}}
    private fun invoiceDialog(type:String){val amount=EditText(this).apply{hint="إجمالي الفاتورة";inputType=2 or 8192};val paid=EditText(this).apply{hint="المدفوع";inputType=2 or 8192};val note=EditText(this).apply{hint="البيان"};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),0,dp(12),0);addView(amount);addView(paid);addView(note)};AlertDialog.Builder(this).setTitle(if(type=="SALE")"فاتورة بيع" else "فاتورة شراء").setView(box).setPositiveButton("حفظ"){_,_->val a=amount.text.toString().toDoubleOrNull()?:0.0;val p=paid.text.toString().toDoubleOrNull()?:0.0;if(a<=0){toast("أدخل الإجمالي");return@setPositiveButton};db.writableDatabase.execSQL("INSERT INTO invoices(type,date,total,paid,note) VALUES(?,?,?,?,?)",arrayOf(type,db.now(),a,p,note.text.toString()));invoices()}.setNegativeButton("إلغاء",null).show()}
    private fun inventory(){setPage("المخزون");body.addView(btn("＋ إضافة صنف جديد"){productDialog()});db.products().forEach{p->val v=card();v.addView(tv(p.name,17f,true));v.addView(tv("المخزون: ${money.format(p.stock)}   •   البيع: ${money.format(p.sellPrice)}   •   الشراء: ${money.format(p.buyPrice)}",14f));if(p.stock<=p.minStock)v.addView(tv("⚠ المخزون منخفض",13f,true,red));v.setOnLongClickListener{confirm("حذف الصنف؟"){db.deleteProduct(p.id);inventory()};true};body.addView(v,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(4),0,dp(4))})}}
    private fun more(){setPage("المزيد");listOf("المصروفات" to {expenses()},"استيراد قاعدة بيانات SQLite" to {pickDatabase()},"فحص قاعدة البيانات" to {checkDb()},"إعدادات التطبيق" to {settings()},"إعادة تحميل البيانات" to {dashboard()}).forEach{(s,f)->val v=card();v.addView(tv(s,17f,true));v.setOnClickListener{f()};body.addView(v,LinearLayout.LayoutParams(-1,dp(68)).apply{setMargins(0,dp(5),0,dp(5))})}}
    private fun expenses(){setPage("المصروفات");body.addView(btn("＋ إضافة مصروف"){expenseDialog()});db.expenses().forEach{e->val v=card();v.addView(tv(e.title,17f,true));v.addView(tv("${money.format(e.amount)} ${e.currency}  •  ${e.date}",14f));body.addView(v,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(4),0,dp(4))})}}
    private fun settings(){setPage("الإعدادات");body.addView(tv("اسم المنشأة",14f,false,muted));val n=EditText(this).apply{setText(db.setting("store_name","بقالة العزي للمواد الغذائية"))};body.addView(n);body.addView(tv("رقم الهاتف",14f,false,muted));val p=EditText(this).apply{setText(db.setting("phone","776425052"));inputType=3};body.addView(p);body.addView(btn("حفظ الإعدادات"){db.setSetting("store_name",n.text.toString());db.setSetting("phone",p.text.toString());toast("تم الحفظ")})}
    private fun customerDialog(old:Customer?=null){val n=EditText(this).apply{hint="اسم العميل *";setText(old?.name.orEmpty())};val p=EditText(this).apply{hint="رقم الهاتف";setText(old?.phone.orEmpty());inputType=3};val note=EditText(this).apply{hint="ملاحظات";setText(old?.notes.orEmpty())};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),0,dp(12),0);addView(n);addView(p);addView(note)};AlertDialog.Builder(this).setTitle(if(old==null)"إضافة حساب" else "تعديل الحساب").setView(box).setPositiveButton("حفظ"){_,_->if(n.text.isBlank())toast("اسم العميل مطلوب")else if(old==null){db.addCustomer(n.text.toString(),p.text.toString(),note.text.toString());accounts()}else{db.updateCustomer(old.id,n.text.toString(),p.text.toString(),note.text.toString());ledger(old.id)}}.setNegativeButton("إلغاء",null).show()}
    private fun chooseCustomerForTx(){val cs=db.customers();if(cs.isEmpty()){toast("أضف حساباً أولاً");return};AlertDialog.Builder(this).setTitle("اختر الحساب").setItems(cs.map{it.name}.toTypedArray()){_,w->transactionDialog(cs[w])}.show()}
    private fun transactionDialog(c:Customer){val a=EditText(this).apply{hint="المبلغ *";inputType=2 or 8192};val note=EditText(this).apply{hint="البيان"};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),0,dp(12),0);addView(a);addView(note)};AlertDialog.Builder(this).setTitle("إضافة عملية — ${c.name}").setView(box).setPositiveButton("عليه"){_,_->saveTx(c,"DEBIT",a,note)}.setNeutralButton("له"){_,_->saveTx(c,"CREDIT",a,note)}.setNegativeButton("إلغاء",null).show()}
    private fun saveTx(c:Customer,type:String,a:EditText,n:EditText){val v=a.text.toString().toDoubleOrNull();if(v==null||v<=0){toast("المبلغ غير صحيح");return};db.addTransaction(c.id,type,v,n.text.toString());ledger(c.id)}
    private fun productDialog(){val n=EditText(this).apply{hint="اسم الصنف *"};val buy=EditText(this).apply{hint="سعر الشراء";inputType=2 or 8192};val sell=EditText(this).apply{hint="سعر البيع";inputType=2 or 8192};val stock=EditText(this).apply{hint="الكمية";inputType=2 or 8192};val min=EditText(this).apply{hint="الحد الأدنى";inputType=2 or 8192};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),0,dp(12),0);listOf(n,buy,sell,stock,min).forEach{addView(it)}};AlertDialog.Builder(this).setTitle("إضافة صنف").setView(box).setPositiveButton("حفظ"){_,_->if(n.text.isBlank())toast("اسم الصنف مطلوب")else try{db.addProduct(n.text.toString(),"",buy.num(),sell.num(),stock.num(),min.num(),"");inventory()}catch(_:Exception){toast("الصنف موجود مسبقاً")}}.setNegativeButton("إلغاء",null).show()}
    private fun expenseDialog(){val t=EditText(this).apply{hint="البيان"};val a=EditText(this).apply{hint="المبلغ";inputType=2 or 8192};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),0,dp(12),0);addView(t);addView(a)};AlertDialog.Builder(this).setTitle("إضافة مصروف").setView(box).setPositiveButton("حفظ"){_,_->val v=a.text.toString().toDoubleOrNull()?:0.0;if(v>0){db.addExpense(t.text.toString(),v,"");expenses()}}.setNegativeButton("إلغاء",null).show()}
    private fun query(sql:String,args:Array<String>?,block:(android.database.Cursor)->Unit){db.readableDatabase.rawQuery(sql,args).use{while(it.moveToNext())block(it)}}
    private fun confirm(message:String,yes:()->Unit){AlertDialog.Builder(this).setMessage(message).setNegativeButton("إلغاء",null).setPositiveButton("موافق"){_,_->yes()}.show()}
    private fun toast(s:String){Toast.makeText(this,s,Toast.LENGTH_SHORT).show()}
    private fun share(c:Customer){val tx=db.transactions(c.id);val text=buildString{append("كشف حساب: ${c.name}\n");append("الهاتف: ${c.phone}\n\n");tx.forEach{append("${it.date} | ${it.type} | ${money.format(it.amount)} | ${it.note}\n")};append("\nالرصيد: ${money.format(c.balance)}")};startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type="text/plain";putExtra(Intent.EXTRA_TEXT,text)},"مشاركة الحساب"))}
    private fun checkDb(){try{toast(if(db.integrityCheck()) "قاعدة البيانات سليمة" else "فشل فحص قاعدة البيانات")}catch(e:Exception){toast("فشل الفحص: ${e.message}")}}
    private fun pickDatabase(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/octet-stream";addCategory(Intent.CATEGORY_OPENABLE)},9001)}
    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode==9001&&resultCode==RESULT_OK&&data?.data!=null){try{val r=DatabaseImportManager.import(this,data.data!!);toast("تم الاستيراد: ${r.message}");dashboard()}catch(e:Exception){toast("فشل الاستيراد: ${e.message}")}}}
    private fun EditText.num()=text.toString().toDoubleOrNull()?:0.0
}
